compressionLevel: mixed

# We need this for when this .yarnrc.yml file is used inside the docker
# container as the output directory (where the tests are ran) is writable, but
# the global cache folder is not.
enableGlobalCache: false
